version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./poke_challenge/:/app/poke_challenge
    env_file: ./docker/local.env
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:poke_db
  db:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=user"
      - "POSTGRES_DB=poke_db"
